WORKDIR: "<path/to/working/diretory>"
SAMPLES: "<path/to/samples>"
REF: "/data2/wittdillon_lab/reference_genomes/water_buffalo/Bubalus_bubalis_genome_NDDB_SH_1.fasta"
ADAPTREMOVE: "/data2/wittdillon_lab/software/adapterremoval-2.3.1/build/AdapterRemoval"
OUTPUT: "<path/to/output/folder>"